# Generated by Django 5.1.2 on 2024-10-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mous', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mou',
            name='is_active',
        ),
        migrations.AddField(
            model_name='activity',
            name='outcome_completed',
            field=models.BooleanField(default=False),
        ),
    ]
