# Generated by Django 5.1.2 on 2024-10-26 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mous', '0002_remove_mou_is_active_activity_outcome_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='outcome_completed',
        ),
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.RemoveField(
            model_name='mou',
            name='department',
        ),
        migrations.AddField(
            model_name='mou',
            name='department',
            field=models.ManyToManyField(to='mous.department'),
        ),
    ]
