# Generated by Django 5.1.2 on 2024-10-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mous', '0003_remove_activity_outcome_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mou',
            name='pdf_file',
            field=models.FileField(default='path/to/default/file.pdf', upload_to='mou_pdfs/'),
        ),
    ]
